version: '3.9'
services: 
    webpage:
       build: 
           context: ./webs/webpage/
           dockerfile: Dockerfile
       volumes: 
           - ./webpage/:/usr/src/
       ports: 
           - 9109:5000
       environment: 
           DEBUG: 1 
           FLASK_HOST: "0.0.0.0"
           FLASK_PORT: 5000
           URLANALYSER_HOST: "urlanalyser"
           URLANALYSER_PORT: 5000
    livesample:
       build: 
           context: ./webs/livesample/
           dockerfile: Dockerfile
       volumes: 
           - ./livesample/:/usr/src/app/
       ports: 
           - 9110:5000
       environment: 
           PORT: 5000
           FLASK_DEBUG: 1
    urlanalyser:
        build:
            context: ./urlanalyser/
            dockerfile: Dockerfile
        volumes: 
            - ./urlanalyser/:/usr/src/
            - ./collection/:/usr/src/tmp/
        environment: 
            DEBUG: False
            FLASK_HOST: "0.0.0.0"
            FLASK_PORT: 5000
            REDIS_HOST: "redis"
            REDIS_PORT: 6379
            SELENIUM_HOST: "selenium-hub"
            SELENIUM_PORT: "4444"
            COLLECTION_PATH: "./usr/src/tmp/"
            UPDATE_DELAY: 3600
        logging:
            driver: "json-file"
            options:
                tag: "urlanalyser"
        deploy:
            mode: replicated
            replicas: 1
    discord-bot:
        build: 
            context: ./discordbot/
            dockerfile: Dockerfile
        logging:
            driver: "json-file"
            options:
                tag: "discord-bot"
        volumes: 
            - ./discordbot/:/usr/src/
        environment: 
           URLANALYSER_HOST: "urlanalyser"
           URLANALYSER_PORT: 5000
           DEBUG: False
    telegram-bot:
        build: 
            context: ./telegrambot/
            dockerfile: Dockerfile
        logging:
            driver: "json-file"
            options:
                tag: "telegram-bot"
        volumes: 
            - ./telegrambot/:/usr/src/
        environment: 
           URLANALYSER_HOST: "urlanalyser"
           URLANALYSER_PORT: 5000
           DEBUG: False
    redis:
        image: redis
        logging:
            driver: "json-file"
    selenium-hub:
      image: selenium/hub
      container_name: selenium-hub
      ports:                
        - "4442:4442"
        - "4443:4443"   
        - "4444:4444"
    firefox:
      image: selenium/node-firefox
      shm_size: 2gb
      depends_on:
        - selenium-hub
      environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      deploy:
        mode: replicated
        replicas: 2
    # chrome:
    #   image: selenium/node-chrome
    #   shm_size: 2gb
    #   depends_on:
    #     - selenium-hub
    #   environment:
    #     - SE_EVENT_BUS_HOST=selenium-hub
    #     - SE_EVENT_BUS_PUBLISH_PORT=4442
    #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
