version: '3.9'
services: 
    webpage:
        build: 
            context: ./webs/webpage/
            dockerfile: Dockerfile
        volumes: 
            - ./webpage/:/usr/src/
        ports: 
            - 9109:5000
        environment: 
            PORT: 5000
            URLANALYSER_PORT: 5000
            FLASK_DEBUG: 1
    livesample:
        build: 
            context: ./webs/livesample/
            dockerfile: Dockerfile
        volumes: 
            - ./livesample/:/usr/src/app/
        ports: 
            - 9110:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
    urlanalyser:
        build:
            context: ./urlanalyser/
            dockerfile: Dockerfile
        volumes: 
            - ./urlanalyser/:/usr/src/
        ports: 
            - 9111:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
    ingenbot:
        build: 
            context: ./ingenbot/
            dockerfile: Dockerfile
        volumes: 
            - ./ingenbot/:/usr/src/
        